### ISSUE TITLE
Create an easy editor for section content

### ISSUE THREAD

**Issue by micchickenburger** [enove/Thriver#10]
Staff members aren't very keen on writing markdown for sections.  Help them out with some compromised interface that allows for some WYSIWYG elements without causing additions of poor code and without incurring a buggy and unpredictable interface.

**Comment by eoghanmcinerney** [comment]
Do we want to create a fully custom UI for this?
Something you'd like me to design?
When does this item need to be completed?

Consider using a prefab GUI like TinyMCE or something?

**Comment by micchickenburger** [comment]
I really like Github's interface.

**Comment by micchickenburger** [comment]
Superseded by issue #103
