### ISSUE TITLE
Fix smooth scroll jitter

### ISSUE THREAD

**Issue by micchickenburger** [enove/Thriver#12]
At times, clicking a link will cause a stutter before the smooth scroll appears.  It's almost as if the page relocates to that location of the destination, then back in less than half a second before beginning the smooth scroll.

**Comment by eoghanmcinerney** [comment]
This is something we should talk about.
Is scrolling to a section the best method?
Or could it be better if say it faded in/out?

If scrolling is the answer:
Observing a flicker of the section it is to scroll to occasionally.
Can we modify the easing of that effect?

**Comment by eoghanTadhg** [comment]
And: Can we add an active class to the navigation list item as it's corresponding section is currently visible in the viewport? Does this because an expensive feature because we have to do additional tests during a scroll event?

**Comment by eoghanTadhg** [comment]
This issue is no longer applicable.
