### ISSUE TITLE
Cross-Browser validation

### ISSUE THREAD

**Issue by micchickenburger** [enove/Thriver#13]
Perform cross-browser testing to ensure compatibility with:

* IE 9, 10, 11
* Edge
* Firefox
* Safari
* Chrome

**Comment by eoghanmcinerney** [comment]
We could leave this item as a reference note to the browser's we will be supporting.
I will be performing cross-browser Quality Assurance upon releasing a given completed module.

I will be checking on the browsers noted above on both PC & Mac.
Will also be testing on Safari in iOS7+ on iPad2+ & iPhone5+

**Comment by eoghanTadhg** [comment]
This issue is no longer applicable as it will be completed as per component to the chandelier branch.
