### ISSUE TITLE
Replace Static Login/Logout & Notifications Content with real data

### ISSUE THREAD

**Issue by micchickenburger** [enove/Thriver#17]
![screen shot 2015-12-26 at 10 25 52 pm](https://cloud.githubusercontent.com/assets/4521230/12008848/a8fd98b8-ac1f-11e5-851f-0828144efe87.png)

There are templates all over for these sections, but the content is missing.  Also, it looks like quite a bit of the content in these sections are static.  I'd like to start building user profiles.

**Comment by eoghanmcinerney** [comment]
So it now seems to be showing correct templates based on being logged in.
Can I assist further on this item at this time?

**Comment by eoghanTadhg** [comment]
This item has been corrected.
