### ISSUE TITLE
Generic Notification Links

### ISSUE THREAD

**Issue by micchickenburger** [enove/Thriver#34]
Generic notifications should link to their hrefs somehow.  For instance, if an action alert is added, the user should be able to click the corresponding notification to view the action alert.  The notification already receives this information in the url attribute; we just need the front-end to inform the user somehow that it's clickable.

**Comment by eoghanTadhg** [comment]
Perhaps this is best accomplished as the donation renew & approval notifications operate?
By placing a button with call to action text such as "View Action Alert"

**Comment by eoghanTadhg** [comment]
I've assigned you to this task, @micchickenburger , as I assume that number value needs to be displayed via a database value.

**Comment by micchickenburger** [comment]
This capability now exists, though there still isn't any notification support.
