### ISSUE TITLE
Providers Section leaving previous county's selection if a new county is selected with multiple available locations

### ISSUE THREAD

**Issue by eoghanTadhg** [enove/Thriver#40]

**Comment by micchickenburger** [comment]
This was by design because I couldn't decide for the user which provider to automatically select.  Do you have any ideas?

**Comment by eoghanTadhg** [comment]
Perhaps we could remove the listing.
I've got to create a state for providers if no location data is available to hide the provider details panel.

Maybe if you select a county with multiple listings, the providers details panel retracts off-canvas and then reappears when a user hovers over a new provider.

**Comment by micchickenburger** [comment]
I'm good with that

**Comment by eoghanTadhg** [comment]
This issue is no longer applicable and is resolved in the Chandelier update.
