### ISSUE TITLE
Child Pages in Work Section: Headlines should carry over icon from parent.

### ISSUE THREAD

**Issue by eoghanTadhg** [enove/Thriver#41]

**Comment by micchickenburger** [comment]
Are you saying an umbrella has nothing to do with State Policy?
![screen shot 2016-03-07 at 9 30 59 am](https://cloud.githubusercontent.com/assets/4521230/13573888/662eb93a-e447-11e5-817b-2792efee571d.png)

**Comment by eoghanTadhg** [comment]
Umbrellas are cool.

**Comment by eoghanTadhg** [comment]
No longer applicable.
