### ISSUE TITLE
Complete 'Get Help' Utility LI click event

### ISSUE THREAD

**Issue by eoghanTadhg** [enove/Thriver#43]
We need to complete the event for the 'Get Help' button in the utility navigation.
@micchickenburger , was hoping you could help.

**Visible on line 55-61 in utility.js:**
`'click li.getHelp': closeAsides,
     'click li.getHelp': function (event) {
           location.href='/#service-providers';
           $('figure.alert').addClass('active').delay(5000).queue(function(){
            $(this).removeClass("active").dequeue();
        });
    }`

We need to scroll down the page to #service-providers and display an alert with content. 
Alerts have their own module where their template can be referenced.

**Comment by micchickenburger** [comment]
Is this still an issue @eoghanTadhg?

**Comment by eoghanTadhg** [comment]
This is no longer a visible issue and the button behaves as expected.
