### ISSUE TITLE
Register Error Element needs to be removed from source code

### ISSUE THREAD

**Issue by eoghanTadhg** [enove/Thriver#47]
Line 6 of account_register.html reads:
`<p id="register-error" style="display:none;"></p>`

I've added a display:none to this element temporarily.
It needs to only be only placed in the markup if error=true.
Then of course we can remove the inline style.

Alternatively it needs to have a class added to the element if error=true, that way I can hide the element unless error=true.

**Comment by micchickenburger** [comment]
Is this still an issue @eoghanTadhg?

**Comment by eoghanTadhg** [comment]
@micchickenburger yes, it seemed to be required in the markup while other validation forms are injected without having a error element in the markup.

**Comment by micchickenburger** [comment]
This element is used to convey registration-related errors to the user.
