### ISSUE TITLE
Question: URL & Nav Active Class on Scroll: Can it change based on a percentage?

### ISSUE THREAD

**Issue by eoghanTadhg** [enove/Thriver#48]
Ideally I think the URL and nav active class would change as a section takes over 50% of the viewport.
However not sure if that's possible.

**Comment by eoghanTadhg** [comment]
And Ideally, I think the active state would be added as a user scrolls through a section even if there scroll event does not come to a full stop.

**Comment by micchickenburger** [comment]
Resolved.
