### ISSUE TITLE
Audit Content in Work Section

### ISSUE THREAD

**Issue by eoghanTadhg** [enove/Thriver#68]
Should it have h2 and h3 listed in table of contents?
Do we collapse with detail/summary?

We need to follow up with content team.

**Comment by eoghanTadhg** [comment]
@micchickenburger This one will require some input/definition from you and WCASA on final content for work section.

**Comment by micchickenburger** [comment]
I'll be manually marking up this content in the near term and will force compliance in the administrative interfaces in the future.
