### ISSUE TITLE
Work Section > Prevention: Child links do not fire standard function when work content is not active.

### ISSUE THREAD

**Issue by eoghanTadhg** [enove/Thriver#70]

**Comment by eoghanTadhg** [comment]
Links not working in numerous child menus.

**Comment by eoghanTadhg** [comment]
@micchickenburger  You might have a look at this, as I know this was an ongoing issue since the Work section links were defined to the appropriated article content.

**Comment by micchickenburger** [comment]
Acknowledged and reproduced.
